hash-format = "sha256"

[[files]]
file = "LICENSE"
hash = "20c17d8b8c48a600800dfd14f95d5cb9ff47066a9641ddeab48dc54aec96e331"

[[files]]
file = "config/openloader/data/Leather Backpacks/data/backpacked/recipes/backpack.json"
hash = "91ef30ea7a57b7561fa3473d9660d95828870e285433787548d570282acb5d36"

[[files]]
file = "config/openloader/data/Leather Backpacks/pack.mcmeta"
hash = "bb685b2164c360187041aaf3d02b78604e967221763cc3a09028d257bd720215"

[[files]]
file = "config/openloader/data/create-simple-storage-recipes-datapack.pw.toml"
hash = "986be95d8a759de996985e32fb313bad07a14346fb2f61c290f9fbffdc25884c"
metafile = true

[[files]]
file = "config/openloader/resources/toms-create-storage.pw.toml"
hash = "7369c0f50de35aa5988bcb1b4f51bb94247b4d15be890b44b254112da1a04d9f"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "e3dfb2478e6bb096667d4ec89b0ddfef627747939373bdefee02f358d6e3dee1"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "a243675bc757485925b293932ee289b9fbcfb3b75bd3ba74eca7603f191cedad"
metafile = true

[[files]]
file = "mods/athena-ctm.pw.toml"
hash = "ead86ab1bacf74c7ad2d28c11157c2982fab4d15d2c25158e77b7491eff3d983"
metafile = true

[[files]]
file = "mods/backpacked-fabric.pw.toml"
hash = "83a32267aa14479c455eb564df451b8a14a6a4148661264193d2ef6aa84a0537"
metafile = true

[[files]]
file = "mods/camera-utils.pw.toml"
hash = "2c7529609ad6edcb330bfa0d9b3a58f2504616d7807c4b6c3d209c19a545f7b9"
metafile = true

[[files]]
file = "mods/carry-on.pw.toml"
hash = "94fbe9655850d99ed2a950e6b59c9cbfabfc21d859c7920c4a8b21101f5981b7"
metafile = true

[[files]]
file = "mods/chipped.pw.toml"
hash = "fd15a165cf8782b21ea9ce958468dbb4bee1fc092fd3d83f901631e075eced75"
metafile = true

[[files]]
file = "mods/cinderscapes.pw.toml"
hash = "54cb55e5f1e39a6b3409399db7d8258c68e8ee64926fa650fb3d74b5cbb9fe42"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "0360f47c1afd7385518db9df5d809344e1bcdc163e940a8744ee61b6d745b6ce"
metafile = true

[[files]]
file = "mods/create-enchantment-industry-fabric.pw.toml"
hash = "5c8ea25c304ea7d269abf6d95d3933c889c111ec33c865bc5031f2ea69aed617"
metafile = true

[[files]]
file = "mods/create-fabric.pw.toml"
hash = "e5bbc96d6d5d6bffb8e36c89bbd1331d923e23fbb87be8bae208d206832adb1c"
metafile = true

[[files]]
file = "mods/create-steam-n-rails.pw.toml"
hash = "2995bd6fc4d6cfb207625005e7392fc09aefe226a0441cceca6687dfc1883ad6"
metafile = true

[[files]]
file = "mods/dcwa.pw.toml"
hash = "e96c71e46932e7060f04e19145977c2ca71686f373273a8fae78f933a37b1b75"
metafile = true

[[files]]
file = "mods/decorative-blocks.pw.toml"
hash = "43ea00d836bef5a72eb2e074e5b0ba534e09d31e41a674c8b3d77f307dfbd619"
metafile = true

[[files]]
file = "mods/ears.pw.toml"
hash = "6a4afd7b42387477795e73b17b8963ea313ce6f8a960343a2579ff0b41544beb"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
hash = "b9cd400ba7e738f6c5e0d4b596d1c9a2b6348bd4f2579c9df4cc865e138f2b59"
metafile = true

[[files]]
file = "mods/emitrades.pw.toml"
hash = "a55d562fcd6be9796e8cc162b83b5745efd83254fae44bf5a4d85d0fe6c97fcb"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "b579df537ada69409b9f1bc6d4dccd2fc0f4962f20068aa61a599d75622c3898"
metafile = true

[[files]]
file = "mods/estrogen.pw.toml"
hash = "0e8813a1aa7130ed082ff8753ed2c64200fa4246fde4ed1522bc76828dfadd91"
metafile = true

[[files]]
file = "mods/extended-cogwheels.pw.toml"
hash = "e5a66f936624909d847060c6aee2cded1300934c5ad1396db173275293dfbf86"
metafile = true

[[files]]
file = "mods/extra-mod-integrations.pw.toml"
hash = "4b5af07a3311d776868ed6f0c22180ab50f224caca07e6fd7b33c6d8bb2ff80d"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "f6f8827bc39d892a56351a6cecd39176addebb2ebf1c608b761b0d1985080b05"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "651e82c2b53b326df742ea36e806f3003e5ad68d1177a09fbe94d9dc7e780471"
metafile = true

[[files]]
file = "mods/farmers-delight-fabric.pw.toml"
hash = "dc4a6ad558baacff8619bcb127784bfa27eb6ca4c177eae12d86b833eca80694"
metafile = true

[[files]]
file = "mods/figura.pw.toml"
hash = "c8d5810420301ff7cdcf1039d672ad7dfb01a77edf219f2f8d5e3689dd9624d6"
metafile = true

[[files]]
file = "mods/framework-fabric.pw.toml"
hash = "afc98470b699a933cbdcc7d95822455596d91864ef14ec21a48f4fdd51d5eb03"
metafile = true

[[files]]
file = "mods/geophilic.pw.toml"
hash = "dff520bc4934ac3bf7fa1b0634c25a8d3b150117d20860f2d13b2d88664c52f1"
metafile = true

[[files]]
file = "mods/handcrafted.pw.toml"
hash = "2e3547b6513fabf4cc51efc2488115ea8297ec0e4845d57abad8d9e1a798b924"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "85daf558c36022a664c9e2bc3d9a9bc21cb9fa62977890f142c20ccc155eae36"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "279b1d659f51d4df30fe741db66d22f8ca447ce30edc8e1b496b10a611143937"
metafile = true

[[files]]
file = "mods/jade-addons-fabric.pw.toml"
hash = "f150264c0991c3faa578a2669ccfb3964850f6d759acc84dad0b545abd9c8915"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "51709a536d48a3aa27af5c0316647dc0dc74be79000ecb5262795bb383c9a204"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "c239c951796882b9c93e649a0dba4f2d95804441faaed707b686381b7a5c67da"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "4cd171d3f5f3e1d2948cb1b0062e742a5e85110c9e9a668f9aed5b0cebcb9c97"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
hash = "db0666dfafeb0790232e8306a468b5725f372114d4bcd9f2743994e62458a3e7"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "669008dbd2508a67f8c409096cf2357de450f26a69494289e5852045ade7d358"
metafile = true

[[files]]
file = "mods/nullscape.pw.toml"
hash = "1f265c12c3649ab889b96bf8a3f5263521e5afc82c66e094983bfd003b3200a2"
metafile = true

[[files]]
file = "mods/open-loader.pw.toml"
hash = "d2f68bad5068b7dd0ff76db5943ac58368be7348a60ceb6e848dc61876c733e1"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
hash = "d8d167c69fa2b57d6ef71f1649da05ac7cbfbc9213b43aeb6e81ed9ffa49a114"
metafile = true

[[files]]
file = "mods/screenshot-to-clipboard.pw.toml"
hash = "da37a60329f2dce95e0563cebd12e6e47f262c6f376873034ff8c76955dc77da"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "1fe2b3aa3fb54a4c449935c7cd74c8a3af1a342e6974bf6154916908ad861d1f"
metafile = true

[[files]]
file = "mods/slice-and-dice.pw.toml"
hash = "89fc4d8fa43ced76ba5452eef196d5986d831ba828921cc133e4fc6139a123f0"
metafile = true

[[files]]
file = "mods/smooth-swapping.pw.toml"
hash = "2b3394fafb201f1b24b6daf60a2c522154732d830844f2c6fc7eb309652ae1ef"
metafile = true

[[files]]
file = "mods/snow-sniffer.pw.toml"
hash = "eb830c14cc047509709e8d3675b3a9def50e17c97a6046c31822679bf10ac393"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "217b07516517c4c01958387192143943f3e9309a0e935828f9f32af771425d66"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "218f67d6bcaae849582618cd3e5eb1d4cac0fd6045115f64340620300e160c11"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
hash = "5f2eebc2182c9bdc5f703666d5b967c05e020dee72a585d1ba7998a6ecd1e800"
metafile = true

[[files]]
file = "mods/toms-storage.pw.toml"
hash = "16533ac83d5cd1cb2708e080ad7996b22a595a7184a034516d46ad871776cd9b"
metafile = true

[[files]]
file = "mods/tooltipfix.pw.toml"
hash = "fe592547ec2aedf1de7add34f747f7845e103de228e2426328e9e60fe93298cc"
metafile = true

[[files]]
file = "mods/trinkets.pw.toml"
hash = "b2e02d1210f025b905299bfc88f895058640158343322641aca2c4875622c992"
metafile = true

[[files]]
file = "mods/villager-pickup.pw.toml"
hash = "07e275417ce97b29745f914c1de6d60bff64a13faece79d4e6951bbbe6925199"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "887875afff72a7db891c8527b93ca9db844b88d53c60920b3ad0da74109a0a6c"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "b6084cee5cd569d8d6145d5690a312e319fbcfe92a9b4b8b665c99262811f179"
metafile = true
